### ISSUE TITLE
statelint returns 'Field not allowed' for nested object fields in state Result field

### ISSUE THREAD

**Issue by foobarbazbuz** [awslabs/statelint#15]
statelint treats nested object properties in a state's `Result` field as invalid when they are valid JSON. The state machine validator in Step Functions treats this as valid ASL.

Given the following definition `definition.json` modified from the Pass state in the [ASL spec](https://states-language.net/spec.html#pass-state):
```json
{
    "StartAt": "No-op",
    "States": {
        "No-op": {
            "Type": "Pass",
            "ResultPath": "$.coords",
            "Result": {
                "foo": {
                    "x-datum": 0.381018,
                    "y-datum": 622.2269926397355
                }
            },
            "End": true
        }
    }
}
```

statelint produces the following:
```
statelint definition.json
2 errors:
 Field "x-datum" not allowed in State Machine.States.No-op.Result.foo
 Field "y-datum" not allowed in State Machine.States.No-op.Result.foo
```

Similarly the following definition `definition-2.json`:
```json
{
    "StartAt": "No-op",
    "States": {
        "No-op": {
            "Type": "Pass",
            "ResultPath": "$.coords",
            "Result": [
                "foo",
                "bar",
                {
                    "bazz": 123
                }
            ],
            "End": true
        }
    }
}
```
returns:
```
statelint definition-2.json
One error:
 Field "bazz" not allowed in State Machine.States.No-op.Result[2]
```

**Comment by timbray** [comment]
Yep, looks like a bug to me.  Need to find a way at the j2119 level to say "anything is OK here."

**Comment by jezhiggins** [comment]
I encountered this same problem in statelint port.  My solution is for rules of the form 

    A Task State MAY have an object field named "ResourceConfig".

(ie an object field which doesn't define a child role)

then create a grandparent role with that field, and then mark that role as allowing any field.  (I suspect Tim and I may be the only two people who can make sense of that sentence.)  I can, if you like, backport my change to Ruby and send you a PR for j2119.

**Comment by wong-a** [comment]
Tested on v0.5.0 with both definitions in the initial issue comment and they are passing validation correctly.
