### ISSUE TITLE
Set non-zero exit code on error?

### ISSUE THREAD

**Issue by dinvlad** [awslabs/statelint#3]
Hi team,

Currently, even if there are errors in the input, statelint exits with code 0. That makes it harder to use it in scripted environments (e.g. for CD via CodeBuild). Could this be fixed in a future release?

Thanks

**Comment by timbray** [comment]
Sorry for ignoring this bug, somehow I didn't get emailed.  Yes, this should be done - will have to figure out how to do that with Ruby :)
