### ISSUE TITLE
Add json manipulations

### ISSUE THREAD

**Issue by nikita-clearscale** [awslabs/statelint#32]
It would be nice if your team added a step which can process input json with [jolt](https://github.com/bazaarvoice/jolt) (or orther json engine).
This open a big feature about json transformation. For example now I can not use `dynamodb` `getItem` step because it produces huge json with `S`, `M`, `N` etc keys. So I can not passed this into code without transfornation and have to write lambda anyway. With jolt situation can be much easier.

**Comment by wong-a** [comment]
This sounds like a request for Amazon States Language itself, not statelint. If you would like to request new additions to the ASL spec, you are welcome to create an issue in the states-language repo.

https://github.com/awslabs/states-language
