### ISSUE TITLE
Any plan to port this to Python

### ISSUE THREAD

**Issue by csabaszilveszter** [awslabs/statelint#36]
All of our linters (including cfn-lint and sam validate) are installed via PIP.

Having ruby installed only to lint this seems overkill.

Asking because I'd contribute.

**Comment by wong-a** [comment]
We don't have any concrete plans to port this to Python at the moment but you are more than welcome to write you own :)

Here is an example of a JS port referenced in #4: 
* https://github.com/wmfs/statelint
* https://github.com/wmfs/tymly-statelint
