### ISSUE TITLE
Fail State specification mismatch

### ISSUE THREAD

**Issue by ghost** [awslabs/statelint#44]
In https://states-language.net/#fail-state: A Fail State **MUST** have a string field named "Error"... A Fail State **MUST** have a string field named "Cause".

In https://github.com/awslabs/statelint/blob/master/data/StateMachine.j2119 string 30, 31:
A Fail State **MAY** have a string field named "Cause".
A Fail State **MAY** have a string field named "Error".

**Comment by timbray** [comment]
The thing to do is to see what the actual service accepts (don't know off the top of my head) and make it consistent with that.

**Comment by wong-a** [comment]
statelint is correct . `Cause` and `Error` are optional fields for the `Fail` state according to the actual service and the AWS documentation.

https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-fail-state.html

**Comment by itstheceo** [comment]
Further to this, statelint does not allow `ErrorPath` or `CausePath` fields on a `Fail` state which is inconsistent with the examples in the official documentation, and on the states-language site. The fields are valid.

**Comment by yaythomas** [comment]
spec updated: these fields are optional: https://states-language.net/#fail-state

`ErrorPath` and `CausePath` available in latest gem (0.6).
