### ISSUE TITLE
There is no rule - A Choice Rule MAY have a field named "Comment"

### ISSUE THREAD

**Issue by ghost** [awslabs/statelint#46]
The new language specification introduced in Workflow studio allows comments in condition branches. Statelint ignores this update, generating an error message like `
Field "Comment" not allowed in State Machine.States.Choice1.Choices[0]`

![image](https://user-images.githubusercontent.com/1640229/122750640-362a1b80-d2a8-11eb-9e3f-aaf347a78ff6.png)

**Comment by timbray** [comment]
Heh, so is field "Comment" allowed in a Choice State child?  (I bet it is.). So someone should change states-language.net/spec.html

**Comment by timbray** [comment]
(and fix statelint)

**Comment by wong-a** [comment]
https://github.com/awslabs/statelint/pull/55
