### ISSUE TITLE
Empty ErrorEquals passes validation

### ISSUE THREAD

**Issue by derek-pryor** [awslabs/statelint#5]
An empty ErrorEquals for a Catch or Retry object passes validation but should be considered invalid.

From https://states-language.net/spec.html#errors
> contain a field named “ErrorEquals” whose value MUST be a non-empty array of Strings

**Comment by timbray** [comment]
Looks like you're correct: https://github.com/awslabs/statelint/blob/master/data/StateMachine.j2119#L34 (recurs)

Thanks, good catch.
