### ISSUE TITLE
Is statelint dead

### ISSUE THREAD

**Issue by zwing99** [awslabs/statelint#50]
I see no comments on #49. Does that mean that this project is dead?

**Comment by embano1** [comment]
I reached out to my colleagues to clarify the state of the project.

**Comment by wong-a** [comment]
Apologies for the delay. This project is still owned by the AWS Step Functions team. We haven't deprecated statelint, but work on it has been delayed due other projects we are prioritizing. Getting this and other 1P tooling up to parity is on our roadmap.

I've raised the issue mentioned above with the team to schedule it for prioritization.
