### ISSUE TITLE
Provide Docker Image

### ISSUE THREAD

**Issue by RafaelWO** [awslabs/statelint#64]
Hey, I would like to use statelint in my CI/CD and for this it would be great to have a Docker image that runs statelint out of the box. Would it be an option to provide a Docker image (e.g. on DockerHub) with statelint?

My current workaround is to use the ruby image and install statelint within the CI.

Happy to create a PR with the Dockerfile :slightly_smiling_face:

**Comment by VaidSaraswat** [comment]
Hi, thank you for using statelint, and for your thoughtful recommendation! Unfortunately we do not plan to vend statelint through Docker at this time. Our recommendation is to keep using your workaround for the time being, and we will communicate any updates to the validation process as they become available.

**Comment by RafaelWO** [comment]
Thanks for your answer! But I guess it's fine if I would create my own repository for this, right? :slightly_smiling_face:

**Comment by yaythomas** [comment]
yes, of course, this the beauty of open-source! thank you for contributing!
