### ISSUE TITLE
Field "Comment" not allowed in nested Choice state

### ISSUE THREAD

**Issue by RafaelWO** [awslabs/statelint#65]
Statelint fails with the following error if a nested `And`/`Or` object within a `Choice` state contains a comment.

```
 Field "Comment" not allowed in State Machine.States.ChoiceStateX.Choices[1].And[1]
```

Although I get no error in the AWS console or the AWS VSCode extension, it is valid in both cases. Who is wrong? :thinking: 

Example choice state:

```json
"ChoiceStateX": {
  "Type": "Choice",
  "Choices": [
    {
      "Variable": "$.value",
      "NumericEquals": 0,
      "Next": "ValueIsZero"
    },
    {
      "And": [
        {
          "Variable": "$.value",
          "NumericGreaterThanEquals": 20
        },
        {
          "Comment": "Foobar",
          "Or": [
            {
              "Variable": "$.foo",
              "IsPresent": true
            },
            {
              "Variable": "$.bar",
              "IsPresent": true
            }
          ]
        }
      ],
      "Next": "ValueInTwenties"
    }
  ],
  "Default": "DefaultState"
}
```

**Comment by RafaelWO** [comment]
> We'll amend statelint to allow for this also.

That's awesome! So I guess I can just stay subscribed to this issue and will get notified if this change is merged/released? :slightly_smiling_face:

**Comment by yaythomas** [comment]
0.8.0, with this fix, published to rubygems
