### ISSUE TITLE
Comparison of strings to 'null' value

### ISSUE THREAD

**Issue by dinvlad** [awslabs/statelint#7]
Hi Team,

I've reported that on AWS forums, but maybe it's also appropriate to post here: currently, there seems to be no way to check that a particular string value equals `null`. I.e. if a previous step returns 'nothing' instead of an empty value, I'd like to check for that in the next choice state. But `statelint` fails validation of such a machine, literally saying that `State Machine.States.XXXX.Branches[0].States.YYYY.Choices[0].StringEquals should be non-null`.

Is that intentional? This limitation is not apparent from the spec.

Thanks

**Comment by timbray** [comment]
Interesting.  To make sure I understand; what you want to check is whether a particular field in a state's input actually exists or not?  If that's true, you're right, it's not currently in the language.  But sounds like a plausible thing to want.

**Comment by dinvlad** [comment]
Actually, it would be nice to support 2 cases:
1) the field does not actually exist. I.e. if I have input with `$.fields` and trying to reference `$.fields.key`, but my `$.fields` is equal to
```
{
  "key1": "value1",
  "key2": "value2"
}
```
(notice, there's no "key" field). 

2) the field exists, but its value is actually `null`. For example, I output something from a Lambda written in Node.js by calling `callback(null, null)`, where the first `null` is error (or rather lack of it), and the second is my actual output. Then I use something like
```
"RunLambda": {
  "Type": "Task",
  "Resource": "arn:aws:lambda:us-east-1:123456789012:function:Lambda",
  "ResultPath": "$.fields.key",
  "Next": "CheckValue"
},
"CheckValue": {
  "Type" : "Choice",
  "Choices": [{
    "Variable": "$.fields.key",
    "StringEquals": null,
    "Next": "DoSomethingAboutNullValue"
  }],
  "Default": "BusinessAsUsual"
}
```
Notice, here I actually compare a valid key to the value `null`. Currently, we can work around that by either throwing an error and handling it with `"Catch"`, or output a special string value instead of `null` (e.g. `"NULL"`). But these still seem like workarounds.

Not sure if (2) is language/runtime-specific, maybe it's just for Java and JavaScript; but Step Functions do seem to understand `null`s, and it's a [valid JSON value](http://www.json.org/))

Hope that makes sense.

**Comment by timbray** [comment]
Interesting.  Yes, JSON's feeble type system does include null as a value, so it's reasonable to want to test against it.  Using "StringEquals" feels initially weird but may make more sense than any other alternative.  You might be able to argue that that idiom not Just Working is a bug.

I'm pretty sure that "absent" and "present but null" are two different things.  Shouldn't be hard to add to the language.

However, for the moment at least the language exists mainly to serve the needs of the Step Functions product, so the best way to get something added to it is to lobby your AWS contact for this as a product feature and get it voted up on our backlog.

**Comment by dinvlad** [comment]
Sounds good, perhaps we'll open a case to add a feature request for an "IsNull" condition.

**Comment by pacey** [comment]
Were there any outcomes or updates on this? An `IsNull` condition would be great!

**Comment by jamesdixon** [comment]
Would love an update on this as well!

**Comment by timbray** [comment]
OK, thanks for the input, everyone.  These are reasonable requests and are on the Step Functions roadmap.  No promises on dates.

**Comment by jakemitchellxyz** [comment]
+1, I also need an IsNull to check if input field exists

**Comment by chrisyorkston** [comment]
This would be a really useful feature.

**Comment by marc-roberts-jg** [comment]
Any updates on this feature?

**Comment by paulfryer** [comment]
Need IsNull

**Comment by TochukwuVictor** [comment]
Would also appreciate this feature.

**Comment by johniwasz** [comment]
Adding more more voice to the chorus for a check for null on a field in a Step Function.

**Comment by artukrap** [comment]
Currently would use this new feature we had it. So +1 definitely for `IsNull`

**Comment by jnfeinstein** [comment]
+1 this is definitely necessary

**Comment by Thana404** [comment]
Would also love to have this feature !

**Comment by dtelaroli** [comment]
2 years later... 😴

**Comment by slootjes** [comment]
My issues are solved with the new Map and Callback features that were recently added. IsNull would still be a very helpful feature though.

**Comment by CMMR2** [comment]
Wow. It's 2020 and this is still an open issue. Please, this is sorely wanted.

**Comment by bondsbw** [comment]
+1

**Comment by matthewhanson** [comment]
+1

**Comment by matthewhanson** [comment]
To expand with my particular use case

I have a Step Function where I provide arguments to each task in the input payload. This payload is passed along between tasks in the payload:

e.g., 
```json
{
   "taskA": {
      "arg1": "val1",
      "arg2": "val2"
   },
   "taskB": {
      "otherarg1": "otherval1",
      "otherarg2": "otherval2"
   }
}
```

In some cases I don't have a need to call a particular task.  If I can add in a Choice field that checks if the arguments for a specific Task exist, then I can run a task only if the input says so.  Otherwise I might create different workflows depending on which tasks I definitely will be running.

Yes, there are other ways to achieve this, I could provide a separate value that is a bool that indicates whether to run a task or not, but having a isNull condition is cleaner and doesn't put additional requirements on the input payload - it can define only the steps it wants to run and other steps are ignored.

**Comment by timbray** [comment]
Just to be clear, I (and the Step Functions team) agree that the omission of null-checking and existence-checking from the States Language and the service is a bug, and we should fix it.  No promises on dates, but we're working on a batch of fixes of these and other irritants.

**Comment by jthomerson** [comment]
Thanks @timbray for the update. Another example to consider when planning those changes:

A function is invoked and could return either a successful response or an error, e.g.

```
// Successful invocation returns:
{
   "successToken": "foo"
}

// Error returns:
{
   "failureType": "invalid-input",
   "failureDetails": "You must provide field 'xyz' in the input"
}
```

Then I want to run a choice after that state to say "if it was successful, do X, but if it had an error, do Y".

Or, one other example: a function should return an object with multiple fields. I want to check the existence of all of the fields in my choice, to make sure all (and not just some) of them were successfully returned before proceeding. I'm sure this will be covered by whatever you already have planned (using the existing `And` definitions), but just wanted to mention it here as a usecase.

**Comment by jeff3754** [comment]
Any updates?

**Comment by victoriangtempus** [comment]
Need isNull

**Comment by lambertrocher** [comment]
+1

**Comment by dave-sims** [comment]
Pleas add isNull

**Comment by yuhadooper** [comment]
Looking for this from the past three 3 years

**Comment by wong-a** [comment]
Thanks to everyone for providing feedback. As Tim mentioned previously, the AWS Step Functions team is working on enhancements to Amazon States Language. Keep an eye on the states language spec for updates: https://github.com/awslabs/states-language

**Comment by bendenoz** [comment]
+1 for isNull

**Comment by NiklasCorneliusKunz** [comment]
We would also greatly appreciate a isNull option!

**Comment by cclusetti** [comment]
+1, adding to the chant

**Comment by cap-akerr** [comment]
Checking for parameter existence in a Choice would be so valuable. Please include this!

**Comment by wong-a** [comment]
The long-awaited `isPresent` and `isNull` Choice Rules are now part of the ASL spec!

`isNull` is does a check against the JSON literal `null` and `isPresent` checks for the existence of a value at the Variable field.

These changes are two of many updates to Amazon States Language released today. To learn more, check out the [updated language specification](https://states-language.net/spec.html#2020-08-11) and this [blog post](https://aws.amazon.com/blogs/aws/aws-step-functions-adds-updates-to-choice-state-global-access-to-context-object-dynamic-timeouts-result-selection-and-intrinsic-functions-to-amazon-states-languages/).

PRs that close this issue:
- https://github.com/awslabs/states-language/pull/18
- https://github.com/awslabs/statelint/pull/40
